// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPZwr4_rJar13xQVEDqrN9ehTAAD7eLI',
    appId: '1:941468631552:web:ce689d0c47781417954ee5',
    messagingSenderId: '941468631552',
    projectId: 'chorepal-88256',
    authDomain: 'chorepal-88256.firebaseapp.com',
    storageBucket: 'chorepal-88256.firebasestorage.app',
    measurementId: 'G-KM6NPP5MX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFAHNi8ls70wnmSHFYA-Zp92vcpuA4iKc',
    appId: '1:941468631552:android:8227ae8203f84ff7954ee5',
    messagingSenderId: '941468631552',
    projectId: 'chorepal-88256',
    storageBucket: 'chorepal-88256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf47GMr5JoPwZsJ6vK5cOJml8jKXwCs9s',
    appId: '1:941468631552:ios:930224773697aeda954ee5',
    messagingSenderId: '941468631552',
    projectId: 'chorepal-88256',
    storageBucket: 'chorepal-88256.firebasestorage.app',
    iosBundleId: 'com.example.chorePal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf47GMr5JoPwZsJ6vK5cOJml8jKXwCs9s',
    appId: '1:941468631552:ios:930224773697aeda954ee5',
    messagingSenderId: '941468631552',
    projectId: 'chorepal-88256',
    storageBucket: 'chorepal-88256.firebasestorage.app',
    iosBundleId: 'com.example.chorePal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoPZwr4_rJar13xQVEDqrN9ehTAAD7eLI',
    appId: '1:941468631552:web:8568b15155aec5e9954ee5',
    messagingSenderId: '941468631552',
    projectId: 'chorepal-88256',
    authDomain: 'chorepal-88256.firebaseapp.com',
    storageBucket: 'chorepal-88256.firebasestorage.app',
    measurementId: 'G-SL4273D8HX',
  );
}
